-- 新建用户表：
CREATE TABLE CISWEB.SYS_USER  ( 
	ID         	VARCHAR(32) NOT NULL,
	USERNAME   	VARCHAR(255),
	LOGINNAME  	VARCHAR(255) NOT NULL,
	PASSWORD   	VARCHAR(32) NOT NULL,
	SEX        	CHARACTER(1),
	ID_CARD    	VARCHAR(18),
	PHONE      	VARCHAR(20),
	MOBILE     	VARCHAR(18),
	EMAIL      	VARCHAR(100),
	CREATOR_ID 	VARCHAR(32),
	CREATE_TIME	DATE,
	UPDATER_ID 	VARCHAR(32),
	UPDATE_TIME	DATE,
	STATE      	DECIMAL(18,2),
	REMARK     	VARCHAR(1000),
	ORG_ID     	VARCHAR(100),
	CORPORATION	VARCHAR(100),
	CONSTRAINT PK_SYS_USER PRIMARY KEY(ID)
)
;
COMMENT ON TABLE CISWEB.SYS_USER IS '用户表'
;
COMMENT ON COLUMN CISWEB.SYS_USER.ID IS 'ID'
;
COMMENT ON COLUMN CISWEB.SYS_USER.USERNAME IS '用户名'
;
COMMENT ON COLUMN CISWEB.SYS_USER.LOGINNAME IS '登录名'
;
COMMENT ON COLUMN CISWEB.SYS_USER.PASSWORD IS '密码'
;
COMMENT ON COLUMN CISWEB.SYS_USER.SEX IS '性别：0女，1男'
;
COMMENT ON COLUMN CISWEB.SYS_USER.ID_CARD IS '身份证'
;
COMMENT ON COLUMN CISWEB.SYS_USER.PHONE IS '电话'
;
COMMENT ON COLUMN CISWEB.SYS_USER.MOBILE IS '手机号'
;
COMMENT ON COLUMN CISWEB.SYS_USER.EMAIL IS '邮箱'
;
COMMENT ON COLUMN CISWEB.SYS_USER.CREATOR_ID IS '创建者ID'
;
COMMENT ON COLUMN CISWEB.SYS_USER.CREATE_TIME IS '创建时间'
;
COMMENT ON COLUMN CISWEB.SYS_USER.UPDATER_ID IS '更新者ID'
;
COMMENT ON COLUMN CISWEB.SYS_USER.UPDATE_TIME IS '更新时间'
;
COMMENT ON COLUMN CISWEB.SYS_USER.STATE IS '状态'
;
COMMENT ON COLUMN CISWEB.SYS_USER.REMARK IS '备注'
;
COMMENT ON COLUMN CISWEB.SYS_USER.ORG_ID IS '机构编号'
;
COMMENT ON COLUMN CISWEB.SYS_USER.CORPORATION IS '法人行'
;

INSERT INTO CISWEB.SYS_USER(ID, USERNAME, LOGINNAME, PASSWORD, SEX, ID_CARD, PHONE, MOBILE, EMAIL, CREATOR_ID, CREATE_TIME, UPDATER_ID, UPDATE_TIME, STATE, REMARK, ORG_ID, CORPORATION)
  VALUES('0', '超级管理员', 'admin', 'c4ca4238a0b923820dcc509a6f75849b', '1', '370112199009022222', '0531-77777777', '15712345678', '143@ww.com1112', NULL, NULL, NULL, NULL, NULL, NULL, '800000000', '999999')
;



-- 角色表
CREATE TABLE CISWEB.SYS_ROLE  ( 
	ROLE_ID    	VARCHAR(32) NOT NULL,
	ROLE_NAME  	VARCHAR(255),
	STATE      	CHARACTER(10),
	REMARK     	VARCHAR(4000),
	CORPORATION	VARCHAR(255),
	CREATE_ID 	VARCHAR(32),
	CREATE_TIME	DATE,
	UPDATER_ID 	VARCHAR(32),
	UPDATE_TIME	DATE,
	CONSTRAINT PK_SYS_ROLE PRIMARY KEY(ROLE_ID)
)
;
COMMENT ON TABLE CISWEB.SYS_ROLE IS '角色表'
;
COMMENT ON COLUMN CISWEB.SYS_ROLE.ROLE_ID IS '角色ID'
;
COMMENT ON COLUMN CISWEB.SYS_ROLE.ROLE_NAME IS '角色名称'
;
COMMENT ON COLUMN CISWEB.SYS_ROLE.STATE IS '状态：0：不启用，1启用'
;
COMMENT ON COLUMN CISWEB.SYS_ROLE.REMARK IS '备注'
;
COMMENT ON COLUMN CISWEB.SYS_ROLE.CORPORATION IS '法人行'
;
COMMENT ON COLUMN CISWEB.SYS_ROLE.CREATE_ID IS '创建ID'
;
COMMENT ON COLUMN CISWEB.SYS_ROLE.CREATE_TIME IS '创建时间'
;
COMMENT ON COLUMN CISWEB.SYS_ROLE.UPDATER_ID IS '更新ID'
;
COMMENT ON COLUMN CISWEB.SYS_ROLE.UPDATE_TIME IS '更新时间'
;

alter table SYS_ROLE add special varchar(32)
;
COMMENT ON COLUMN CISWEB.SYS_ROLE.special IS '特殊说明'
;

INSERT INTO CISWEB.SYS_ROLE(ROLE_ID, ROLE_NAME, STATE, REMARK, CORPORATION, CREATE_ID, CREATE_TIME, UPDATER_ID, UPDATE_TIME)
  VALUES('0', '超级管理员角色', '1', '', '999999', NULL, NULL, NULL, NULL)
;


-- 用户角色表
CREATE TABLE CISWEB.SYS_USER_ROLE  ( 
	USER_ID	VARCHAR(32),
	ROLE_ID	VARCHAR(32),
	STATE  	CHARACTER(2),
	REMARK 	VARCHAR(300)  ,
CONSTRAINT FK_ROLE_ID foreign KEY(ROLE_ID) references SYS_ROLE(ROLE_ID),
CONSTRAINT FK_PERMISSION_ID foreign KEY(USER_ID) references SYS_USER(ID)
	)
;
COMMENT ON TABLE CISWEB.SYS_USER_ROLE IS '用户角色表'
;
COMMENT ON COLUMN CISWEB.SYS_USER_ROLE.USER_ID IS '用户ID'
;
COMMENT ON COLUMN CISWEB.SYS_USER_ROLE.ROLE_ID IS '角色ID'
;
COMMENT ON COLUMN CISWEB.SYS_USER_ROLE.STATE IS '状态：0：不启用，1启用'
;
COMMENT ON COLUMN CISWEB.SYS_USER_ROLE.REMARK IS '备注'
;

INSERT INTO CISWEB.SYS_USER_ROLE(USER_ID, ROLE_ID, STATE, REMARK) 
	VALUES('0', '0', '1', '')
;


-- 权限表
CREATE TABLE CISWEB.SYS_PERMISSION  ( 
	ID         	VARCHAR(32) NOT NULL,
	NAME       	VARCHAR(255),
	CODE       	VARCHAR(255),
	PARENT_ID  	VARCHAR(32),
	URL        	VARCHAR(4000),
	ICON_CLS   	VARCHAR(255),
	TYPE       	CHARACTER(1),
	-- PAGE       	VARCHAR(32),
	CREATOR_ID 	VARCHAR(32),
	CREATE_TIME	DATE,
	UPDATER_ID 	VARCHAR(32),
	UPDATE_TIME	DATE,
	STATE      	CHARACTER(1),
	REMARK     	VARCHAR(4000),
	CONSTRAINT PK_SYS_PERMISSION PRIMARY KEY(ID)
)
;
COMMENT ON TABLE CISWEB.SYS_PERMISSION IS '权限表'
;
COMMENT ON COLUMN CISWEB.SYS_PERMISSION.ID IS 'ID'
;
COMMENT ON COLUMN CISWEB.SYS_PERMISSION.NAME IS '名称'
;
COMMENT ON COLUMN CISWEB.SYS_PERMISSION.CODE IS '编码'
;
COMMENT ON COLUMN CISWEB.SYS_PERMISSION.PARENT_ID IS '父级ID'
;
COMMENT ON COLUMN CISWEB.SYS_PERMISSION.URL IS 'URL地址'
;
COMMENT ON COLUMN CISWEB.SYS_PERMISSION.ICON_CLS IS '图标'
;
COMMENT ON COLUMN CISWEB.SYS_PERMISSION.TYPE IS '类型 ，m:菜单，b:按钮'
;
-- COMMENT ON COLUMN CISWEB.SYS_PERMISSION.PAGE IS '页面'
-- ;
COMMENT ON COLUMN CISWEB.SYS_PERMISSION.CREATOR_ID IS '创建者ID'
;
COMMENT ON COLUMN CISWEB.SYS_PERMISSION.CREATE_TIME IS '创建时间'
;
COMMENT ON COLUMN CISWEB.SYS_PERMISSION.UPDATER_ID IS '更新者ID'
;
COMMENT ON COLUMN CISWEB.SYS_PERMISSION.UPDATE_TIME IS '更新时间'
;
COMMENT ON COLUMN CISWEB.SYS_PERMISSION.STATE IS '状态，0不启用，1启用'
;
COMMENT ON COLUMN CISWEB.SYS_PERMISSION.REMARK IS '备注'
;



-- 角色权限表
CREATE TABLE CISWEB.SYS_ROLE_PERMISSION  ( 
	ROLE_ID      	VARCHAR(32),
	PERMISSION_ID	VARCHAR(32),
	STATE        	CHARACTER(2),
	REMARK       	VARCHAR(300)  ,
CONSTRAINT FK_ROLE_ID foreign KEY(ROLE_ID) references SYS_ROLE(ROLE_ID),
CONSTRAINT FK_PERMISSION_ID foreign KEY(PERMISSION_ID) references SYS_PERMISSION(ID)
	)
;

COMMENT ON TABLE CISWEB.SYS_ROLE_PERMISSION IS '角色权限表'
;
COMMENT ON COLUMN CISWEB.SYS_ROLE_PERMISSION.ROLE_ID IS '角色ID'
;
COMMENT ON COLUMN CISWEB.SYS_ROLE_PERMISSION.PERMISSION_ID IS '权限ID'
;
COMMENT ON COLUMN CISWEB.SYS_ROLE_PERMISSION.STATE IS '状态：0：不启用，1启用'
;
COMMENT ON COLUMN CISWEB.SYS_ROLE_PERMISSION.REMARK IS '备注'
;


-- 字典表
CREATE TABLE CISWEB.SYS_DICT  ( 
	ID         	VARCHAR(32) NOT NULL,
	NAME       	VARCHAR(100),
	CODE       	VARCHAR(100),
	GROUP      	VARCHAR(100),
	DESC       	VARCHAR(500),
	ORDER      	VARCHAR(18),
	DEL        	CHARACTER(1),
	CREATOR_ID 	VARCHAR(32),
	CREATE_TIME	DATE,
	UPDATER_ID 	VARCHAR(32),
	UPDATE_TIME	DATE,
	CONSTRAINT PK_SYS_DICT PRIMARY KEY(ID)
)
;
COMMENT ON TABLE CISWEB.SYS_DICT IS '字典表'
;
COMMENT ON COLUMN CISWEB.SYS_DICT.ID IS 'ID'
;
COMMENT ON COLUMN CISWEB.SYS_DICT.NAME IS '名称'
;
COMMENT ON COLUMN CISWEB.SYS_DICT.CODE IS '编码'
;
COMMENT ON COLUMN CISWEB.SYS_DICT.GROUP IS '组'
;
COMMENT ON COLUMN CISWEB.SYS_DICT.DESC IS '描述'
;
COMMENT ON COLUMN CISWEB.SYS_DICT.ORDER IS '排序'
;
COMMENT ON COLUMN CISWEB.SYS_DICT.DEL IS '是否启用，0不启用，1启用'
;
COMMENT ON COLUMN CISWEB.SYS_DICT.CREATOR_ID IS '创建者ID'
;
COMMENT ON COLUMN CISWEB.SYS_DICT.CREATE_TIME IS '创建时间'
;
COMMENT ON COLUMN CISWEB.SYS_DICT.UPDATER_ID IS '更新者ID'
;
COMMENT ON COLUMN CISWEB.SYS_DICT.UPDATE_TIME IS '更新时间'
;